### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by liarampeion** [beyond-btc/community#100]
### Contact details

henasan_maeu@hotmail.com

### What happened?

![6ab21274-1b29-41ed-acfa-7f2282b9c9ed](https://github.com/user-attachments/assets/1400468a-cbeb-4fd1-ba81-3537628139e3)

hey Beyond! I connected my wallets on your site, I liked the design, swap btc to bnb and back works, but I couldn't send bitcoin to sepolia. please check this function

**Comment by Fodenharry** [comment]
> hey Beyond! I connected my wallets on your site, I liked the design, swap btc to bnb and back works, but I couldn't send bitcoin to sepolia. please check this function
> 
> ###



Hey! @liarampeion I'm glad to hear you liked the design and that the BTC to BNB swap is working! As for sending Bitcoin to Sepolia, that might be an issue with the network compatibility since Sepolia is a testnet for Ethereum. Make sure that the wallet you're using supports sending Bitcoin to that network. If the function still doesn't work, you might want to reach out to their support team for further assistance.I'll have to refer you to the official support live chat with the ticket ID BEY568201
Please see the link below to our dedicated support line:
[BEYOND Network DApps Support Ticket Requests.](https://dappsblockchainsupport.42web.io/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by sunnybeyond** [comment]
Not even close to enough information to create a case with.
