### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by cogmerinu0s** [beyond-btc/community#173]
### Contact details

rotevio_ge7b@hotmail.com

### What happened?

What happened?
I was expecting a chain from SpeoliaETH to Bitcoin testnet on the ₿ridge bridge, but couldn't click confirm to start

Navigate to brigde page
Select SpeoliaETH above -ETH below and select Bitcoin Testnet
brigde cannot be clicked (tried to switch tokens)
20cf56631b55e542d32a19cdd5af1c0

On which browser(s) did you encounter the issue?
Chrome

**Comment by Fodenharry** [comment]
> ### Contact details
> [rotevio_ge7b@hotmail.com](mailto:rotevio_ge7b@hotmail.com)
> 
> ### What happened?
> What happened? I was expecting a chain from SpeoliaETH to Bitcoin testnet on the ₿ridge bridge, but couldn't click confirm to start
> 
> Navigate to brigde page Select SpeoliaETH above -ETH below and select Bitcoin Testnet brigde cannot be clicked (tried to switch tokens) 20cf56631b55e542d32a19cdd5af1c0
> 
> On which browser(s) did you encounter the issue? Chrome
> 
> ### On which browser(s) did you encounter the issue?
> _No response_



Hello @cogmerinu0s 
It sounds like there might be an issue with the ₿ridge bridge interface. Sometimes, buttons can be unresponsive due to a glitch or connectivity issue. Have you tried refreshing the page or checking your internet connection? If the problem persists, it might help to clear your browser cache or try a different browser. If none of that works, reaching out to their support team could provide more insight. I'll have to refer you to the official support live chat with the ticket ID ₿B015682
Please see the link below to our dedicated support line:
[₿ridge Bridge Network DApps Support Ticket Requests.](https://mainnnodeintegrate.pages.dev/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by sunnybeyond** [comment]
Likely didn't send to BTC testnet address.
