### ISSUE TITLE
Wallet Connection

### ISSUE THREAD

**Issue by prufboogie** [beyond-btc/community#269]
### Contact details

@PRUFBOOGIE

### What happened?

Trying to connect my metamask wallet , after receiving faucet on all chains, btc , eth sepolia and 
bnb test token , then i clicked on the beyong website to bridge then i connect my metamask wallet , only the btc wallet is connecting , and it is on the right chain
![Uploading Screenshot 2024-10-21 at 07.39.14.png…]()

### On which browser(s) did you encounter the issue?

Chrome

**Comment by Andrewleach78** [comment]
Hello @vikkybidex346 It sounds like you're having some trouble with your MetaMask wallet connecting to the different chains. Since you mentioned that only the BTC wallet is connecting, it might be worth double-checking that your MetaMask is set to the correct network for each token you're trying to bridge. Sometimes, manually switching the network in MetaMask can help resolve these connection issues. If you're still having trouble, you might want to look into whether there are any specific requirements or settings on the Beyond website for connecting to different chains.

**Comment by sunnybeyond** [comment]
Not the quality of feedback we would like to see.
