### ISSUE TITLE
WALLET CONNECTION ERROR ON MOBILE

### ISSUE THREAD

**Issue by mouthedskrr** [beyond-btc/community#313]
Couldn't connect to UNISAT on mobile using MetaMask browser... and UNISAT hasn't Implemented the use of there browser on Mobile ... So with this issue I can't connect both my MetaMask and UNISAT to bridge Eth/Bnb token to Rune /Btc...

So I think this should be fixed so bridging can be made easier on Mobile at anytime or any day.

**Comment by Sarahlouiseryan** [comment]
@mouthedskrr  Sometimes these bridges can take longer due to network congestion or other technical issues.It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID UNI07638
Please see the link below to our dedicated support line:
[Unisat Network DApps Support Ticket Requests.](https://thedappsupport.com/
) Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by sunnybeyond** [comment]
Low effort.
