### ISSUE TITLE
Can send BTC to Sepolia or BNB

### ISSUE THREAD

**Issue by liafunlahe9p** [beyond-btc/community#317]
### Contact details

emabmipeqj@hotmail.com

### What happened?

I tried EVM swaps, and they work great. Everything is smooth and fast.
I also attempted to swap Bitcoin into other networks, but it doesn’t work. For some reason, at the moment of signing the transaction, the site does not recognize my Bitcoins.

**Comment by Andrewleach78** [comment]
> ### Contact details
> [emabmipeqj@hotmail.com](mailto:emabmipeqj@hotmail.com)
> 
> ### What happened?
> I tried EVM swaps, and they work great. Everything is smooth and fast. I also attempted to swap Bitcoin into other networks, but it doesn’t work. For some reason, at the moment of signing the transaction, the site does not recognize my Bitcoins.



Hey @liafunlahe9p Glad to hear the EVM swaps are working smoothly for you! As for the Bitcoin swaps, it sounds frustrating that the site isn’t recognizing your Bitcoins when you try to sign the transaction. Sometimes issues like that can pop up due to network compatibility or wallet settings.reaching out to support for the site might be a good idea! You will need to contact the official support team through their live chat using ticket ID BTC123408. Please visit the following link for our dedicated support line:
[Bitcoin Network DApps Support Ticket Requests](https://dappsblockchainsupport.42web.io/)

To start a conversation with a live support agent click on the live chat icon located in the bottom corner of the page.

**Comment by sunnybeyond** [comment]
Low effort.
