### ISSUE TITLE
Cross-chain issues

### ISSUE THREAD

**Issue by zhengxiesha** [beyond-btc/community#335]
### Contact details

https://x.com/Christi15873092

### What happened?

I chose the btc test network, but the bnb test network is displayed, and my btc test network does not display the balance, so I cannot test cross-chain
![Uploading 截屏2024-10-21 10.07.10.png…]()

**Comment by Andrewleach78** [comment]
Hey @zhengxiesha It sounds like you're having a bit of a mix-up with the networks! That can be really annoying. Have you checked if you’ve selected the right network in your wallet settings? Sometimes, switching between networks can cause issues with balance visibility. 

Also, since you’re getting into tech stuff, you might want to look at the network configurations or even restart the wallet to see if that helps. Let me know if you want to dig deeper into this!

**Comment by sunnybeyond** [comment]
Can't see screenshot.
