### ISSUE TITLE
THE CLOSURE OF THE BRIDGE - RUNES/BRC-20

### ISSUE THREAD

**Issue by presspositive** [beyond-btc/community#409]
### Contact details

https://twitter.com/MaykonLeon2419

### What happened?

I made bridges from ETH Sepolia to BTC, using the Runes and BRC-20 options. Several bridges, around 18, are already four days old and have not been completed. The status remains as pending. This is preventing other bridges from being built. Below is an image of the screen.
![BUG Beyond](https://github.com/user-attachments/assets/5313159c-2057-47d9-be29-993256c0ea17)

### On which browser(s) did you encounter the issue?

Metamask, Edge

**Comment by Dappsnode** [comment]
@presspositive It sounds like you're having quite a bit of trouble with those pending bridges. Since you've already had issues with discrepancies and delays before, it might be worth reaching out to the support team.I'll have to refer you to the official support live chat with the ticket ID BEY07638
Please see the link below to our dedicated support line:
[Beyond Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
