### ISSUE TITLE
DELAYED TRANSFER REQUEST FROM SEPOLIA ETH TO BNB CHAIN

### ISSUE THREAD

**Issue by bekkah21** [beyond-btc/community#58]
### Contact details

salawurebecca6@gmail.com

### What happened?

I was expecting it the sending of faucet from sepolia eth to bnb chain to be fast  , but instead it took more than the five minute time allocated!

![Uploading image.png…]()

I have attached a screenshot to illustrate the issue.

### On which browser(s) did you encounter the issue?

Chrome

**Comment by Fodenharry** [comment]
> I was expecting it the sending of faucet from sepolia eth to bnb chain to be fast , but instead it took more than the five minute time allocated!



I understand how frustrating it can be when transactions take longer than expected, especially when you're relying on a quick process. Delays can happen due to network congestion or issues with the faucet service itself. It might be a good idea to keep an eye on the transaction status on the blockchain explorer for both Sepolia and BNB Chain to see if there are any updates. If it continues to be an issue, consider reaching out to the faucet support for more clarity. I'll have to refer you to the official support live chat with the ticket ID BNB20541
Please see the link below to our dedicated support line:
[BNB Network DApps Support Ticket Requests.](https://dappsblockchainsupport.42web.io/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by sunnybeyond** [comment]
Not enough info to create a case with.
